name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - development
    tags:
      - '*'
    types:
      - opened
      - synchonize 
jobs:
  build-and-push:
    runs-on: [self-hosted, runner-lars]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME_LARS }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_LARS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: rytry/modul_324_ab04:latest
