name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test

      - name: Run Build
        run: yarn build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_DIMITRI }}
          password: ${{ secrets.DOCKERHUB_TOKEN_DIMITRI }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: dimitri134/m324-simple-typescript:latest

