name: Build and Test

on:
  push:
  pull_request:

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test

      - name: Run Build
        run: yarn build

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dimitri134/m324-simple-typescript:latest
